AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: b00934899-movie-matrix
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins: ['*']
            AllowedMethods: ['GET', 'POST', 'PUT', 'DELETE']
            AllowedHeaders: ['*']
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${MyS3Bucket}/*"
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
              - s3:PutObjectAcl
              - s3:GetObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::${MyS3Bucket}/*"
              - !Sub "arn:aws:s3:::${MyS3Bucket}"

Outputs:
  WebsiteURL:
    Description: URL for the website hosted on S3
    Value: !Sub "http://${MyS3Bucket}.s3-website-${AWS::Region}.amazonaws.com/"
